on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

name: SonarQube & Trivy Scan

jobs:
  Analysis:
    name: SonarQube Code Analysis
    runs-on: ubuntu-latest
    steps:
    - name: Checking out
      uses: actions/checkout@master
      with:
        fetch-depth: 0  # Disabling shallow clone for better reporting relevance
    - name: SonarQube Scan
      uses: sonarsource/sonarqube-scan-action@master
      env:
        SONAR_TOKEN: ${{ secrets.SONARQUBE_TOKEN }}
        SONAR_HOST_URL: ${{ secrets.SONARQUBE_HOST }}
      with:
        args: >
          -Dsonar.projectVersion=0.1.0
          -Dsonar.projectKey=msc-app

  ScanDeps:
    name: Trivy Scan Dependencies
    stage: scan
    image:
      name: ubuntu:24.04
    steps:
    - name: Install Dependencies
      run: |
        apt-get update
        apt-get install -y wget apt-transport-https gnupg lsb-release
        wget -qO - https://aquasecurity.github.io/trivy-repo/deb/public.key | gpg --dearmor | sudo tee /usr/share/keyrings/trivy.gpg > /dev/null
        echo "deb [signed-by=/usr/share/keyrings/trivy.gpg] https://aquasecurity.github.io/trivy-repo/deb generic main" | sudo tee -a /etc/apt/sources.list.d/trivy.list
        apt-get install trivy
        trivy plugin install github.com/umax/trivy-plugin-sonarqube
    - name: Scan Dependencies with Trivy
      run: |
        trivy fs --security-checks=vuln --vuln-type=library --exit-code=0 --format=json --output=trivy-deps-report.json .
        trivy sonarqube trivy-deps-report.json > sonar-deps-report.json
    - name: Upload Trivy and SonarQube Reports
      uses: actions/upload-artifact@v3
      with:
        name: trivy-sonarqube-reports
        path: |
          trivy-deps-report.json
          sonar-deps-report.json

  ScanCode:
    name: Trivy Scan Code
    stage: scan
    image: sonarsource/sonar-scanner-cli
    needs:
      - ScanDeps
    steps:
    - name: Run SonarScanner
      run: |
        sonar-scanner -D sonar.externalIssuesReportPaths="sonar-deps-report.json"