"""Schemas for the Attack Path Graph feature.

The graph nodes/edges are deterministically derived from existing CWE/CAPEC/EPSS/KEV/inventory
data on every read; the optional narrative is generated by an AI provider on demand and
persisted on the vulnerability document (mirroring the ai_assessment pattern).
"""
from __future__ import annotations

from typing import Any, Literal

from pydantic import BaseModel, Field

from app.schemas.ai import AIProviderLiteral

NodeType = Literal[
    "entry",
    "asset",
    "package",
    "cve",
    "cwe",
    "capec",
    "exploit",
    "impact",
    "fix",
]

LikelihoodLevel = Literal["very_low", "low", "medium", "high", "very_high", "unknown"]
ExploitMaturity = Literal["theoretical", "poc", "functional", "high", "unknown"]
Reachability = Literal["confirmed", "likely", "unknown", "not_reachable"]


class AttackPathNode(BaseModel):
    id: str
    type: NodeType
    label: str
    description: str | None = None
    severity: str | None = None
    metadata: dict[str, Any] | None = None

    model_config = {"populate_by_name": True}


class AttackPathEdge(BaseModel):
    source: str
    target: str
    label: str | None = None

    model_config = {"populate_by_name": True}


class AttackPathLabels(BaseModel):
    likelihood: LikelihoodLevel = "unknown"
    exploit_maturity: ExploitMaturity = Field(
        default="unknown",
        alias="exploitMaturity",
        serialization_alias="exploitMaturity",
    )
    reachability: Reachability = "unknown"
    privileges_required: str | None = Field(
        default=None,
        alias="privilegesRequired",
        serialization_alias="privilegesRequired",
    )
    user_interaction: str | None = Field(
        default=None,
        alias="userInteraction",
        serialization_alias="userInteraction",
    )
    business_impact: str | None = Field(
        default=None,
        alias="businessImpact",
        serialization_alias="businessImpact",
    )

    model_config = {"populate_by_name": True}


class AttackPathGraph(BaseModel):
    nodes: list[AttackPathNode]
    edges: list[AttackPathEdge]
    labels: AttackPathLabels
    disclaimer: str
    generated_at: str = Field(alias="generatedAt", serialization_alias="generatedAt")

    model_config = {"populate_by_name": True}


class AttackPathNarrative(BaseModel):
    provider: AIProviderLiteral | str
    language: str
    summary: str
    generated_at: str = Field(alias="generatedAt", serialization_alias="generatedAt")
    token_usage: dict[str, int] | None = Field(
        default=None, alias="tokenUsage", serialization_alias="tokenUsage"
    )
    triggered_by: str | None = Field(
        default=None, alias="triggeredBy", serialization_alias="triggeredBy"
    )

    model_config = {"populate_by_name": True}


class AttackPathResponse(BaseModel):
    vulnerability_id: str = Field(alias="vulnerabilityId", serialization_alias="vulnerabilityId")
    graph: AttackPathGraph
    narrative: AttackPathNarrative | None = None

    model_config = {"populate_by_name": True}


class AttackPathRequest(BaseModel):
    """Body for POST /vulnerabilities/{id}/attack-path (kicks off AI narrative generation)."""

    provider: AIProviderLiteral
    language: str | None = None
    additional_context: str | None = Field(
        default=None,
        alias="additionalContext",
    )
    triggered_by: str | None = Field(
        default=None,
        alias="triggeredBy",
    )

    model_config = {"populate_by_name": True}


class AttackPathSubmitResponse(BaseModel):
    status: str
    vulnerability_id: str = Field(alias="vulnerabilityId", serialization_alias="vulnerabilityId")

    model_config = {"populate_by_name": True}
